<?php

$operators  = [
	'vn'=>[
		'vietnamobile'=>null,
	],
	'gb'=>[
		'ee'=>null,
		'lycamobile'=>null,
		'o2'=>null,
		'orange'=>null,
		'three'=>null,
		'tmobile'=>null,
		'vodafone'=>null,
	],
	'se'=>[
		'comviq'=>null,
		'lycamobile'=>null,
		'telenor'=>null,
	],
	'es'=>[
		'lycamobile'=>null,
		'yoigo'=>null,
	],
	'ru'=>[
		'beeline'=>null,
		'lycamobile'=>null,
		'megafon'=>null,
		'mts'=>null,
		'mtt'=>null,
		'patriot'=>null,
		'rostelecom'=>null,
		'tele2'=>null,
		'tinkoff'=>null,
		'vtbmobile'=>null,
		'yota'=>null,
	],
	'ro'=>[
		'vodafone'=>null,
	],
	'pt'=>[
		'vodafone'=>null,
		'lycamobile'=>null,
	],
	'pl'=>[
		'tmobile'=>null,
		'orange'=>null,
	],
	'ph'=>[
		'smart'=>null,
		'globe telecom'=>null,
	],
	'nl'=>[
		'lycamobile'=>null,
		'lmobiel'=>null,
		'lebara'=>null,
	],
	'md'=>[
		'moldcell'=>null,
		'orange'=>null,
	],
	'mx'=>[
		'telcel'=>null,
	],
	'lt'=>[
		'tele2'=>null,
	],
	'lv'=>[
		'tele2'=>null,
		'lmt'=>null,
	],
	'la'=>[
		'beeline'=>null,
		'etl'=>null,
		'laotel'=>null,
		'unitel'=>null,
	],
	'kz'=>[
		'activ'=>null,
		'altel'=>null,
		'beeline'=>null,
		'mobile'=>null,
		'tele2'=>null,
	],
	'id'=>[
		'axis'=>null,
		'indosat'=>null,
		'smartfren'=>null,
		'telkomsel'=>null,
		'three'=>null,
	],
	'hk'=>[
		'china mobile'=>null,
		'csl'=>null,
		'smartone'=>null,
		'three'=>null,
	],
	'de'=>[
		'lycamobile'=>null,
	],
	'ge'=>[
		'beeline'=>null,
		'geocell'=>null,
		'magticom'=>null,
		'silknet'=>null,
	],
	'fr'=>[
		'lebara'=>null,
		'lycamobile'=>null,
		'sfr'=>null,
	],
	'fi'=>[
		'dna'=>null,
		'elisa'=>null,
	],
	'fi'=>[
		'dna'=>null,
		'telia'=>null,
		'tele2'=>null,
	],
	'dk'=>[
		'lycamobile'=>null,
	],
];

#print_r($operators);
?>